# Generated by Django 4.1.4 on 2022-12-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField(max_length=1000)),
                ('created', models.DateTimeField()),
                ('edited', models.DateTimeField()),
                ('published', models.IntegerField(choices=[(0, 'DRAFT'), (1, 'PUBLISHED')])),
            ],
        ),
    ]
